baseurl = "/"
languageCode = "en-us"
theme = "term"

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  title = 'This is the posts section'
  url = '/posts/'
  weight = 1
[[menu.main]]
  identifier = 'about'
  name = 'about'
  title = 'This is the about section'
  url = '/about/'